const UI_STRINGS = {
  activity: 'Activity',
  compareWith: 'Compare with',
  noComparison: 'No comparison',
  primary: 'primary',
  comparisonLegend: 'comparison',
  noDataForActivity: 'No data for this activity.',
  fitActivity: 'FIT Activity',
  comparison: 'Comparison',
  manualActivityData: 'Manual Activity Data',
  heartRateZoneProfile: 'Heart Rate Zone Profile',
  recovery: 'Recovery',
  endurance: 'Endurance',
  aerobic: 'Aerobic',
  anaerobic: 'Anaerobic',
  maxZone: 'Max zone',
  heartRateZonesDisabled: 'Heart-rate zones are disabled. Enter a dated profile above to enable zone analysis.',
  heartRateZonesInfo: 'Zones based on max HR {0} bpm. Time is estimated from elapsed record deltas.',
  heartRateZonesCustomInfo: 'Zones based on custom watch thresholds and max HR {0} bpm. Time is estimated from elapsed record deltas.',
  averageHeartRate: 'Average HR (bpm)',
  maximumHeartRate: 'Maximum HR (bpm)',
  notAvailable: 'Not available',
  saveHeartRate: 'Save HR',
  effectiveFrom: 'Effective from',
  auto: 'Auto',
  select: 'Select',
  age: 'Age',
  years: 'years',
  sex: 'Sex',
  currentlyApplied: 'Currently applied:',
  dataQualityNoteTitle: '⚠ Data Quality Note:',
  dataQualityNote: 'Power metrics are motion-estimated (from speed, altitude, and mass) and may be physiologically implausible, especially peak values. These figures and derived metrics (NP, IF, TSS, xPower, RI, BikeStress, Decoupling) should be disregarded for training-load decisions. Use heart-rate trends and effort perception instead.',
  zoneStarts: 'Zone {0} starts',
  recordsLabel: 'Records',
  sessionsLabel: 'Sessions',
  distanceKm: 'Distance (km)',
  durationHms: 'Duration (h:m:s)',
  avgSpeedKmh: 'Avg Speed (km/h)',
  maxSpeedKmh: 'Max Speed (km/h)',
  avgPowerW: 'Avg Power (W)',
  maxPowerW: 'Max Power (W)',
  normalizedPowerW: 'Normalized Power (W)',
  intensityFactorIf: 'Intensity Factor (IF)',
  tssScore: 'TSS',
  xPowerGcW: 'xPower (GC) (W)',
  riGc: 'RI (GC)',
  bikeStressGc: 'BikeStress (GC)',
  decouplingIntervals: 'Decoupling % (Intervals)',
  trimp: 'TRIMP',
  hrTss: 'hrTSS',
  avgHrBpm: 'Avg HR (bpm)',
  maxHrBpm: 'Max HR (bpm)',
  elevationGainM: 'Elevation Gain (m)',
  elevationLossM: 'Elevation Loss (m)',
  gpsPointsLabel: 'GPS Points',
  samples: 'Samples',
  min: 'Min',
  avg: 'Avg',
  beatsPerMinute: 'bpm',
  kilometersPerHour: 'km/h',
  decimalSeparator: '.',
  median: 'Median',
  p95: 'P95',
  max: 'Max',
  male: 'Male',
  female: 'Female',
  other: 'Other',
  ftp: 'FTP',
  noGpsStatsAvailable: 'No GPS stats available.',
  manualSummaryHint: 'Manual summary values are used in metrics and analysis. A heart-rate chart requires time-series samples.',
  autoCalcInfo: 'Auto-calc estimates power from the saved rider and bike mass, speed, GPS altitude, and distance when power-meter data is unavailable. The last saved masses are reused for the next ride. FTP is used for IF/TSS on activity summaries. The latest profile effective on an activity date is used.',
  maximumHrShort: 'Maximum HR',
  restingHeartRate: 'Resting HR',
  watts: 'watts',
  riderMass: 'Rider mass (kg)',
  bikeMass: 'Bike mass (kg)',
  wheelCircumference: 'Wheel circumference (mm)',
  requiredForEstimatedPower: 'required for estimated power',
  autoCalculate: 'Auto-calc',
  saveZones: 'Save Zones',
  speedVsDistance: 'Speed vs Distance',
  heartRateVsDistance: 'Heart Rate vs Distance',
  altitudeVsDistance: 'Altitude vs Distance',
  gpsRoute: 'GPS Route',
  interactiveMap: 'Interactive Map',
  colorRouteBy: 'Color route by',
  speed: 'Speed',
  heartRate: 'Heart Rate',
  segment: 'Segment',
  altitude: 'Altitude',
  terrainLegend: 'Terrain segments',
  terrain: 'Terrain',
  showTerrainBands: 'Show terrain segments on charts',
  segmentDetails: 'Segment details',
  duration: 'Duration',
  distance: 'Distance',
  grade: 'Grade',
  effort: 'Effort',
  elevation: 'Elevation',
  laps: 'Laps',
  segments: 'Segments',
  time: 'Time',
  power: 'Power',
  virtualPower: 'vPower',
  lap: 'Lap',
  climb: 'Climb',
  descent: 'Descent',
  flat: 'Flat',
  stopped: 'Stopped',
  technical: 'Technical descent',
  mapTiles: 'Map tiles from OpenStreetMap.',
  aiAnalysis: 'AI Analysis',
  loadingAnalysis: 'Loading analysis...',
  analyzeActivity: 'Analyze Activity',
  analyzeAgain: 'Analyze Again',
  reanalyze: 'Re-analyze',
  analyzing: 'Analyzing...',
  followUpChat: 'Follow-up Chat',
  followUpPlaceholder: 'Ask a follow-up question about this activity.',
  send: 'Send',
  noMessages: 'No messages yet. Ask a follow-up after analysis.',
  clickAnalyze: 'Click Analyze Activity to analyze this ride.',
  noActivityLoaded: 'No activity loaded. Try refreshing.',
  noActivitySelected: 'No activity selected.',
  noActivityDataForAnalysis: 'No activity data available for analysis.',
  enterFollowUp: 'Enter a follow-up question.',
  thinking: 'Thinking...',
  saving: 'Saving...',
  calculating: 'Calculating...',
  error: 'Error: {0}',
  chatFailed: 'Chat failed.',
  coach: 'Coach',
  you: 'You',
  olderAnalysis: 'Analyzed with an older version. Re-analyze for updated insights.',
  wheelPrompt: 'Type your current wheel circumference above to see a suggested value.',
  wheelCalibrationEvidence: 'Based on recent rides ({0} km of trusted GPS distance), the recorded distance differs by {1}%.',
  wheelSuggestion: 'Wheel circumference is probably closer to {0} mm than {1} mm. Click Save Zones to keep it.',
  useWheelSuggestion: 'Use {0} mm',
  wheelApplied: 'Applied. Click Save Zones to keep it.',
  dismiss: 'Dismiss',
  mapZoomHint: '{0} + scroll to zoom',
  mapLoadFailed: 'Map library failed to load. Run npm install in fit-visualizer.',
  noGpsPoints: 'No GPS points found in this FIT file.',
  generateTranslations: 'Generate {0} translations with Copilot',
  translationsAvailable: 'Translations for {0} are not installed.',
  generateTranslationsConfirm: 'Send the FIT Visualizer UI text to the selected language model to generate a local {0} translation bundle?',
  generate: 'Generate',
  translationGenerating: 'Generating translations...',
  translationGenerated: 'Translations for {0} were generated and saved locally.',
  compareWithAI: 'Compare with AI',
  compareAgain: 'Compare Again',
  comparing: 'Comparing...',
  removeComparison: 'Remove Comparison',
  removingComparison: 'Removing...',
  clickCompare: 'Click Compare with AI to compare these two activities.',
  noComparisonsYet: 'No saved comparisons yet for this activity.',
};

function localizeUi(localize) {
  const translate = typeof localize === 'function' ? localize : (text) => text;
  return Object.fromEntries(Object.entries(UI_STRINGS).map(([key, text]) => [key, translate(text)]));
}

function formatUi(template, ...values) {
  return String(template || '').replace(/\{(\d+)\}/g, (_, index) => String(values[Number(index)] ?? ''));
}

module.exports = { UI_STRINGS, localizeUi, formatUi };